### PR TITLE
[DO-49] adding bucket permissions to the template

### PR DESCRIPTION
**Pull request by simplyadrian**

### CODE REVIEW

**Comment by simplyadrian** [comment]
@sapiensantiquus please have a look

**Comment by simplyadrian** [comment]
@sapiensantiquus @notyost BUMP

**Comment by sapiensantiquus** [comment]
Sorry - What is the need for this change? It looks like this was parameterized and now it's not?

**Comment by simplyadrian** [comment]
@sapiensantiquus this was an addition to allow s3 perms to the shared bucket for creds. The template did not have this support. This is a stop gap until we can decompose the template to use the s3 role and probably the IAM role in the near future.

**Comment by sapiensantiquus** [comment]
Okay. That works then. Merge when ready.

**Pull request merged**
